<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">

		<title>Strayboots | Admin</title>

		<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Roboto:400,300,500,700" />
		<? if (isset($assetsCache)) echo '<link rel="stylesheet" type="text/css" href="/' . $assetsCache . '.css" />'; else $this->assets->outputCss('style') ?>

	</head>
	<body<?= empty($bodyClass) ? '' : " class=\"{$bodyClass}\"" ?>>
<?php
if ($hiddenWrapper):
echo $this->getContent();
else: ?>
		<div id="wrapper">
			<? $this->partial('partials/navbar') ?>

			<div id="page-wrapper" class="gray-bg dashbard-1">
				<? $this->partial('partials/header') ?>
				<?= $this->getContent() ?>
			</div>
		</div>
<? endif ?>

<?
	if (isset($assetsCache))
		echo '<script type="text/javascript" src="/' . $assetsCache . '.js"></script>';
	else
		$this->assets->outputJs('script');
?>

<? if (!empty($msgs = $this->flash->getMessages())): ?>
		<script>
			$(function(){
				<? $x = 0; foreach ($msgs as $type => $msg):
					foreach ($msg as $m): ?>
					setTimeout(function(){
						toastr.<?= $type ?>('Strayboots', "<?= $this->escaper->escapeHtmlAttr($m) ?>");
					}, <?= 500 + $x++ * 1000 ?>);
				<? endforeach; endforeach ?>
			});
		</script>
<? endif ?>
<? if (isset($googleMaps)): ?>
	<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=<?= $googleMaps ?>&callback=gmapInit&libraries=places&language=en&region=US"></script>
<? endif ?>
<? if (isset($vimeo)): ?>
	<script type="text/javascript" src="https://player.vimeo.com/api/player.js"></script>
<? endif ?>
<script type="text/javascript">
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create','UA-7559873-20','auto');ga('send','pageview');
</script>
<script type="text/javascript">var google_conversion_id=1027606727,google_conversion_label="8We6CKOB8GoQx5GA6gM",google_custom_params=window.google_tag_params,google_remarketing_only=true;</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
	</body>
</html>