<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<h1>Points</h1>
	<p>
		<a href="<?= $this->url->get('points/new') ?>" class="btn btn-success">Add a new point</a>
	</p>
</div>

<?= $this->getContent() ?>

<script type="text/javascript">
window.pointTypes=<?= json_encode($pointTypes, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;
window.countries=<?= json_encode($countries, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;
window.cities=<?= json_encode($cities, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;
</script>

<div class="table-responsive">
	<table class="table table-striped table-hover table-custom table-options" id="points-list">
		<thead>
		<tr>
			<th>#</th>
			<th>Internal Name</th>
			<th>Name</th>
			<th>Type</th>
			<th>City / Country</th>
			<th>Long / Lat</th>
			<th>Questions</th>
			<th>Hunt Points</th>
			<th>Actions</th>
		</tr>
		</thead>
	</table>
</div>