		<div class="content-wrapper section-wrapper">
			<div class="container">
				<div class="row">
					<div class="col-md-12 col-sm-12">
						<h1 class="twolines"><?= $t->_('Your Scavenger Hunt Challenges') ?></h1>
						<h2 class="normal twolines"><?= $t->_('Strategize, build your own route, and score as many points as possible!') ?></h2>
						<?= $this->partial('play/strategy_list') ?>
					</div>
				</div>
			</div>
		</div>
