<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<div class="container">
		<h1>My Orders</h1>
		<ol class="breadcrumb">
			<li>
				<?= $this->tag->linkTo(['', "Home"]) ?>
			</li>
			<li class="active">
				<?= $this->tag->linkTo(['orders', "<b>My Orders</b>"]) ?>
			</li>
		</ol>
	</div>
</div>

<div class="container">
	<?= $this->getContent() ?>

	<div class="table-responsive">
		<table class="table table-striped table-hover table-custom table-options" id="orders-list">
			<thead>
			<tr>
				<!--th>#</th-->
				<th>Name</th>
				<th>Created</th>
				<th>Hunts</th>
				<th>Actions</th>
			</tr>
			</thead>
		</table>
	</div>
</div>