<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<div class="container">
<? $orderName = htmlspecialchars($order->name) ?>
		<h1><?= $orderName ?> Hunts</h1>
		<ol class="breadcrumb">
			<li>
				<?= $this->tag->linkTo(['', "Home"]) ?>
			</li>
			<li>
				<?= $this->tag->linkTo(['orders', "My Orders"]) ?>
			</li>
			<li class="active">
				<?= $this->tag->linkTo(['order_hunts/' . $order->id, $orderName . ' Hunts']) ?>
			</li>
		</ol>
	</div>
</div>

<div class="container">

	<?= $this->getContent() ?>
	<script type="text/javascript">window.orderId=<?= $order->id ?></script>

	<div class="table-responsive">
		<table class="table table-striped table-hover table-custom table-options" id="orderhunts-list">
			<thead>
			<tr>
				<!--th>#</th-->
				<th>Hunt</th>
				<th>Players</th>
				<th>Teams</th>
				<th>Start</th>
				<th>Finish</th>
				<th>Expire</th>
				<th>Actions</th>
			</tr>
			</thead>
		</table>
	</div>
</div>
