<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?= $this->tag->linkTo(["event_emails", "Back"]) ?></li>
		</ul>
	</nav>
</div>

<div class="page-header">
	<h1>
		Edit <?= [
				'Danielle Post Event Email Players',
				'Danielle Post Event Email Client',
				'Nikki Post Event Email',
				'Shauna Post Event Email',
				'Post Event Email'
			][$email_id] ?>
	</h1>
</div>

<?= $this->getContent() ?>

<?php
	echo $this->tag->form([
		"event_emails/save",
		"autocomplete" => "off",
		"class" => "form-horizontal xxx"
	]);
?>

<style>
.form-horizontal.xxx {
	visibility: hidden;
}
.note-editor {
	min-height: 0;
}
.form-group textarea {
	min-height: 200px;
	resize: vertical;
}
</style>

<div class="form-group">
	<label for="fieldTitle" class="col-sm-2 control-label">Title</label>
	<div class="col-sm-10 col-lg-8">
		<?= $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldHTML" class="col-sm-2 control-label">HTML</label>
	<div class="col-sm-10 col-lg-8">
		<?= $this->tag->textArea(["html", "size" => 30, "class" => "form-control", "id" => "fieldHTML"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldTitle" class="col-sm-2 control-label">Text</label>
	<div class="col-sm-10 col-lg-8">
		<?= $this->tag->textArea(["text", "size" => 30, "class" => "form-control", "id" => "fieldText"]) ?>
	</div>
</div>

<?= $this->tag->hiddenField('email_id') ?>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?= $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
	</div>
</div>

<?= $this->tag->endForm() ?>
