		<div class="content-wrapper section-wrapper">
			<div class="container">
				<div class="row">
					<div class="col-md-12 col-sm-12">
						<h1><?= $t->_('FAQ') ?></h1>
						<div id="faq">
							<div class="q"><?= $t->_('What is your support phone number?') ?></div>
							<div class="a">
								<?= $t->_('877-787-2929') ?>
							</div>
							<div class="q"><?= $t->_('How are points calculated?') ?></div>
							<div class="a">
								<?= $t->_('Correct answer - Full points<br>Correct answer with a hint - Half points<br>Skip - No points') ?>
							</div>
							<div class="q"><?= $t->_('How much time do I have for this?') ?></div>
							<div class="a">
								<?= $t->_('Once you activate your game, you will have 2 hours to complete this activity.') ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
