		<div class="content-wrapper section-wrapper">
			<div class="container">
				<div class="row">
					<div class="col-md-12 col-sm-12">
						<h1><?= $t->_('FAQ') ?></h1>
						<div id="faq">
							<div class="q">How much time does it take?</div>
							<div class="a">You will have 2 hours to complete your scavenger hunt.</div>
							<div class="q">How much walking is involved?</div>
							<div class="a">Usually 2-2.5 miles, but no more than 10 minutes between each challenge.</div>
							<div class="q">How much does it cost?</div>
							<div class="a">This is a Pay What You Want scavenger hunt, so it's really up to you! (the average payment is $20 USD per person)</div>
							<div class="q">Where do I start the hunt?</div>
							<div class="a">Check your first challenge to know where to go.</div>
							<div class="q">Where do I end the hunt?</div>
							<div class="a">Most of our hunts are built as a round trip, but anyway the end location is near your starting location.</div>
							<div class="q">How are points calculated?</div>
							<div class="a">Correct answer - Full points<br>Correct answer with a hint - Half points<br>Skip - No points</div>
							<div class="q">A challenge or location wasn’t there or had changed and I was unable to get the answer. Will I be docked points?</div>
							<div class="a">Nope! We can manually add your points. Just skip the challenge and shoot us an email.</div>
							<div class="q">Page not responding or not loading?</div>
							<div class="a">Refresh your browser, or give it a few seconds, it will come up.</div>
							<div class="q">Problem uploading photos?</div>
							<div class="a">Take advantage of our unique chat feature! Just upload your photos there and we will add your points.</div>
							<div class="q">What should I do if something goes wrong?</div>
							<div class="a">Give us a call at 877-787-2929 and someone from our staff can assist you.</div>
						</div>
					</div>
				</div>
			</div>
		</div>
