		<div class="content-wrapper section-wrapper">
			<div class="container">
				<div class="row">
					<div class="col-md-12 col-sm-12">
						<h1><?= $t->_('FAQ') ?></h1>
						<div id="faq">
							<div class="q"><?= $t->_('What is your support phone number?') ?></div>
							<div class="a">
								<?= $t->_('877-787-2929') ?>
							</div>
							<? if ($orderId == 2651) :?>
								<div class="q"><?= $t->_('How much time do I have for this?') ?></div>
								<div class="a">
									<?= $t->_('Once you activate your game, you will have 2 hours to complete this activity.') ?>
								</div>
							<? else :?>
								<div class="q"><?= $t->_('I need to switch phones') ?></div>
								<div class="a">
									<?= $t->_('Simply re-enter your Leader team-specific activation code on another phone, and the hunt will pick up where you left off.') ?>
								</div>
								<div class="q"><?= $t->_('The app is not responding') ?></div>
								<div class="a">
									<?= $t->_('Refresh your browser. If the browser reloads the same screen after entering activation code, go into browser settings and accept cookies.') ?>
								</div>
								<div class="q"><?= $t->_('How are points calculated?') ?></div>
								<div class="a">
									<?= $t->_('Correct answer - Full points<br>Correct answer with a hint - Half points<br>Skip - No points') ?>
								</div>
								<div class="q"><?= $t->_('A challenge or location wasn’t there or had changed and I was unable to get the answer. Will I be docked points?') ?></div>
								<div class="a">
									<?= $t->_('Nope! We can manually add your points to your team if you shoot us a call.') ?>
								</div>
							<? endif; ?>
						</div>
					</div>
				</div>
			</div>
		</div>
