<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?= $this->tag->linkTo(['hunts', 'Hunts']) ?></li>
		</ul>
	</nav>
</div>


<div class="page-header">
	<h1>
		Routes for <span style="font-size:80%"><?= $this->tag->linkTo(['hunts/edit/' . $id, htmlspecialchars($hunt->name)]) ?></span>
	</h1>
	<p>
		<a href="#" id="addBtn" class="btn btn-success"><i class="fa fa-plus"></i></a>
	</p>
</div>
<script type="text/javascript">window.hunt=<?= json_encode($hunt->toArray(), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;window.huntPoints=<?= $huntPoints ?></script>

<?= $this->getContent() ?>

<?php
	echo $this->tag->form([
		'hunts/saveRoutes',
		'autocomplete' => 'off',
		'class' => 'form-horizontal'
	]);
?>

<?= $this->tag->hiddenField(['routes', 'id' => 'routesField']) ?>
<?= $this->tag->hiddenField('id') ?>

<div id="routes">
	
</div>

<div class="form-group">
	<div class="col-sm-12">
		<?= $this->tag->submitButton(['Save', 'class' => 'btn btn-default']) ?>
	</div>
</div>

<?= $this->tag->endForm() ?>

<script type="text/javascript">window.pointsCoordinates=<?= $coordinates ?></script>
