<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?= $this->tag->linkTo(['hunts', 'Hunts']) ?></li>
		</ul>
	</nav>
</div>


<div class="page-header">
	<h1>
		Routes for <span style="font-size:80%"><?= $this->tag->linkTo(['hunts/edit/' . $id, htmlspecialchars($hunt->name)]) ?></span>
	</h1>
	<p>
		<a href="#" id="addBtn" class="btn btn-success"><i class="fa fa-plus"></i></a>
	</p>
</div>
<script type="text/javascript">window.hunt=<?= json_encode($hunt->toArray(), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;window.huntPoints=<?= $huntPoints ?></script>

<?= $this->getContent() ?>

<?php
	echo $this->tag->form([
		'hunts/saveRoutes',
		'autocomplete' => 'off',
		'class' => 'form-horizontal'
	]);
?>

<?= $this->tag->hiddenField(['routes', 'id' => 'routesField']) ?>
<?= $this->tag->hiddenField('id') ?>

<div id="routes">
	
</div>

<div class="form-group">
	<div class="col-sm-12">
		<?= $this->tag->submitButton(['Save', 'class' => 'btn btn-default']) ?>
	</div>
</div>

<?= $this->tag->endForm() ?>
<div class="modal fade" id="add-notes" tabindex="-1" role="dialog" aria-labelledby="codesLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form id="form-notes" action="">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
					<h4 class="modal-title">Notes</h4>
				</div>
				<div class="modal-body" style="font-size:20px">
					<div class="row">
						<div class="col-md-12 col-sm-12">
							<div class="old-notes"></div>
							<textarea name="notes" rows="5" cols="50"></textarea>
							<input type="hidden" name="route-id">
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-primary">Save</button>
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">window.pointsCoordinates=<?= $coordinates ?></script>
