
		<nav class="navbar-default navbar-static-side" role="navigation">
			<div class="sidebar-collapse">
				<ul class="nav metismenu" id="side-menu">
					<li class="nav-header">
						<div class="logo-element">
							<a href="<?= $this->url->get('') ?>">Strayboots</a>
						</div>
					</li>
					<li<? if ($controllerName == 'index')echo ' class="active"' ?>>
						<a href="index.html"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboards</span> <span class="fa arrow"></span></a>
						<ul class="nav nav-second-level">
							<li<? if ($controllerName == 'index')echo ' class="active"' ?>><a href="<?= $this->url->get('') ?>">Dashboard</a></li>
						</ul>
					</li>
					<li<? if (in_array($controllerName, ['orders', 'order_hunts', 'teams']))echo ' class="active"' ?>>
						<a href="<?= $this->url->get('orders') ?>"><i class="fa fa-shopping-cart"></i> <span class="nav-label">Orders</span></a>
					</li>
				</ul>

			</div>
		</nav>
