		<div class="content-wrapper">
			<div class="container">
				<h1>All Routes Lead to Midtown Scavenger Hunt</h1>
				<h2>Activate your hunt</h2>
				<div class="col-sm-12">
					<div id="activation-wrapper" class="clearfix">
						<?= $this->tag->form(["/", "id" => "activation-form"]) ?>

							<?= $this->tag->emailField(['email', 'required' => "required", 'class' => "answer", 'id' => "emailField", 'placeholder' => "Email"]) ?>

							<?= $this->tag->textField(['activation', 'required' => "required", 'class' => "answer", 'id' => "activationField", 'placeholder' => "Activation Code"]) ?>
							
							<div style="padding:20px 0">
								<?= $this->tag->submitButton(["Start the hunt!", "class" => "submit subxbtn"]) ?>
								<? /*<br><br><br>
								<a class="submit subxbtn" href="<?= $this->url->get('ncr/register') ?>" style="background:#2ea9e0">Register a new team</a> */ ?>
							</div>

							<div class="atos" style="margin-top:10px">
								By signing up, you agree to Strayboots <a href="http://www.strayboots.com/terms-of-service" target="_blank">Terms of Use</a> and <a href="http://www.strayboots.com/privacy-policy" target="_blank">Privacy Policy</a>
							</div>

							<div class="atos help" style="margin-top:30px">
								For assistance, please call <a href="tel:877-787-2929">877-787-2929</a>
							</div>

						<?= $this->tag->endForm() ?>

					</div>
				</div>
			</div>
		</div>
