		<div class="content-wrapper section-wrapper show" id="playground" style="visibility:visible">
			<div class="container">
				<div class="inner-content">
					<div class="question">
						<b>For <s>20</s> 10 points</b><br>		
						This is an example of the question text
					</div>
					<div class="hint-title">Hint</div>
					<div class="hint">This is an example of the hint text</div>
					<div id="answer-form-wrapper" class="clearfix">
						<form action="/play" id="main-form" onsubmit="return false" autocomplete="off" method="post">
							<input type="text" id="answerField" name="answer" value="" class="answer" required="required" placeholder="Answer">
							<input type="submit" value="Submit" class="submit subxbtn">							
						</form>
					</div>
				</div>
			</div>
		</div>
