<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?= $this->tag->linkTo(["clients", "Back"]) ?></li>
		</ul>
	</nav>
</div>

<div class="page-header">
	<h1>
		Edit client
	</h1>
</div>

<?= $this->getContent() ?>

<?php
	echo $this->tag->form([
		"clients/save",
		"autocomplete" => "off",
		"class" => "form-horizontal"
	]);
?>

<div class="form-group">
	<label for="fieldEmail" class="col-sm-2 control-label">Email</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldCompany" class="col-sm-2 control-label">Company</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["company", "size" => 30, "class" => "form-control", "id" => "fieldCompany"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldPassword" class="col-sm-2 control-label">Password</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldFirstName" class="col-sm-2 control-label">First Name</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["first_name", "size" => 30, "class" => "form-control", "id" => "fieldFirstName"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldLastName" class="col-sm-2 control-label">Last Name</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["last_name", "size" => 30, "class" => "form-control", "id" => "fieldLastName"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldPhone" class="col-sm-2 control-label">Phone</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["phone", "size" => 30, "class" => "form-control", "id" => "fieldPhone"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldNotes" class="col-sm-2 control-label">Notes</label>
	<div class="col-sm-10">
		<?= $this->tag->textArea(["notes", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldNotes"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldActive" class="col-sm-2 control-label">Active</label>
	<div class="col-sm-10 checkbox-inline">
		<?= $this->tag->checkField(["active", "value" => 1, "id" => "fieldActive"]) ?>
	</div>
</div>

<?= $this->tag->hiddenField("id") ?>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?= $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
	</div>
</div>

<?= $this->tag->endForm() ?>
