<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<h1>
		Clients
	</h1>
	<p>
		<a href="<?= $this->url->get('clients/new') ?>" class="btn btn-success">Add a new client</a>
	</p>
</div>

<?= $this->getContent() ?>

<div class="table-responsive">
	<table class="table table-striped table-hover table-custom table-options" id="clients-list">
		<thead>
		<tr>
			<th>#</th>
			<th>Email</th>
			<th>Company</th>
			<th>Name</th>
			<th>Phone</th>
			<th>Created</th>
			<th>Active</th>
			<th>Orders</th>
			<th>Actions</th>
		</tr>
		</thead>
	</table>
</div>
