<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<h1>
		Question types
	</h1>
	<p>
		<a href="<?= $this->url->get('question_types/new') ?>" class="btn btn-success">Add a new question type</a>
	</p>
</div>

<?= $this->getContent() ?>

<div class="table-responsive">
	<table class="table table-striped table-hover table-custom table-options" id="questiontypes-list">
		<thead>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Type</th>
			<th>Score</th>
			<th>Custom</th>
			<th>Limit Answers</th>
			<th>Questions</th>
			<th>Actions</th>
		</tr>
		</thead>
	</table>
</div>