		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
<? if (isset($timeToEnd)): ?>
					<div class="pull-right visible-xs" style="margin:12px 10px 0 0">
						<a class="endtimer-link" style="font-size:18px;"></a>
					</div>
<? endif ?>
					<a class="navbar-brand logo" href="<?= defined('OVERRIDE_STANDARDLOGIN') && isset($currentURL) ? $currentURL : $this->url->get(isset($ncr) ? '/ncr' : '/') ?>">
<? if (isset($customLogo)): ?>
						<img src="<?= $customLogo ?>" alt="" class="customlogo">
<? else: ?>
						<img src="/img/logo.png" alt="Strayboots">
<? endif ?>
					</a>
				</div>
				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-right">
<? if (isset($timeToEnd)): ?>
						<li id="end-timer" data-seconds="<?= $timeToEnd ?>" class="hidden-xs"><a class="endtimer-link"></a></li>
<? endif ?>
<? if (isset($teamStatus) && isset($user_info)): ?>
						<li class="visible-xs teaminfo">
							<?= $t->_('Email: %email%', ['email' => $user_info['email']]) ?><br>
							<?= $t->_('Team: %team%', ['team' => $teamStatus['name']]) ?><br>
							<?= $t->_('Activation code: %code%', ['code' => $user_info['activation']]) ?>
						</li>
<? endif ?>
<? /*if (isset($ncr)): ?>
						<li style="display:block"><a href="<?= $this->url->get('ncr') ?>"><?= $t->_('Login') ?></a></li>
						<li style="display:block"><a href="<?= $this->url->get('ncr/register') ?>"><?= $t->_('Register') ?></a></li>
<? else:*/ ?>
						<li><a href="<?= defined('OVERRIDE_STANDARDLOGIN') && isset($currentURL) ? $currentURL : $this->url->get(isset($ncr) ? '/ncr' : '/') ?>"><?= $t->_('Home') ?></a></li>
<? //endif ?>
					<? if (!$loggedIn): ?>
						<? if (defined('OVERRIDE_STANDARDLOGIN')): ?>
							<li><a href="javascript:;" onclick="$('#temp-faq').modal('show');"><?= $t->_('FAQ') ?></a></li>
						<? else :?>
							<li><a href="<?= $this->url->get('faq') ?>"><?= $t->_('FAQ') ?></a></li>
						<? endif ?>
					<? else :?>
						<li><a href="<?= $this->url->get('faq') ?>"><?= $t->_('FAQ') ?></a></li>
					<? endif ?>
<? if ($loggedIn): ?>
<? if (!$mapDisabled): ?>
						<li class="m-map"><a href="<?= $this->url->get('map') ?>"><?= $t->_('Map') ?></a></li>
<? endif ?>
						<li class="m-chat"><a href="<?= $this->url->get('chat') ?>"><?= $t->_('Chat') ?></a></li>
<? if (!$leaderboardDisabled): ?>
						<li class="m-leaderboard"><a href="<?= $this->url->get('leaderboard') ?>"><?= $t->_('Leaderboard') ?></a></li>
<? endif ?>
<? if ($isLeader): ?>
						<li class="visible-xs"><a href="<?= $this->url->get('index/rename') ?>"><?= $t->_('Rename Team') ?></a></li>
<? if ($isMultiHunt): ?>
						<li><a href="<?= $this->url->get('index/chooseHunt') ?>"><?= $t->_('Choose Hunt') ?></a></li>
<? endif ?>
<? endif ?>
						<li><a href="<?= $this->url->get('index/logout') ?>" id="logout-btn"><?= $t->_('Log Out') ?></a></li>
<? endif ?>
						<li class="visible-xs">
							<select onchange="document.location.href='?lang='+this.value" class="form-control" id="lang-selector">
								<? $def = (int)$this->config->defLang; $langs = array_merge(['en'], array_values((array)$this->config->altLang)); if (!isset($langs[$def])) $def = 0; ?>
								<? foreach ($langs as $i => $l): if (defined('SAUDI_ARABIA_HUNT') && ($i === 1 || $i === 2)) continue; ?>
									<option class="lang-<?= $i ?>" value="<?= $i ?>"<?= $i === $multiLang ? ' selected' : '' ?>><?= $t->_('lang.' . $l) ?></option>
								<? endforeach ?>
							</select>
						</li>
					</ul>
				</div>
			</div>
		</nav>
<? if (isset($teamStatus) && !isset($hideHeaderStatus)): ?>
<? if ($controllerName != 'map'): ?>
		<div style="height:90px"></div>
<? endif ?>
		<div id="header-score">
			<!--i class="fa fa-trophy"></i-->
<? if (!isset($noScore)): ?>
	<? if (!$leaderboardDisabled): ?>
		<div id="place">
			<div><?= $t->_('Place') ?></div>
			<span><?= $teamStatus['position'] ?></span>
		</div>
	<? endif ?>
	<div id="team-score">
		<div><?= $t->_('Team Score') ?></div>
		<span><?= $teamStatus['score'] ?></span>
	</div>
<? endif ?>
<? if (isset($question)): ?>
			<div>
				<div><?= $t->_('Progress') ?></div>
				<span style="padding:0 15px"><?= $question['currentPos'] ?> / <?= $question['numQuestions'] ?></span>
			</div>
<? endif ?>
<? if (isset($qtimeout)): ?>
			<div class="timeout-progress hidden">
				<div></div>
				<time></time>
			</div>
<? endif ?>
		</div>
<? endif ?>

<style type="text/css">
	#temp-faq #faq .q {
		font-weight: 600;
		font-size: 20px;
		margin-bottom: 5px;
	}
	#temp-faq #faq .a {
		font-size: 14px;
	}
	#temp-faq #faq {
		color: #000;
	}
	#temp-faq #faq .a + .q {
		margin-top: 20px;
	}
</style>
<div class="modal fade" id="temp-faq" tabindex="-1" role="dialog" aria-labelledby="codesLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
				<h4 class="modal-title" ><?= $t->_('FAQ') ?></h4>
			</div>
			<div class="modal-body" style="font-size:20px">
						<div class="row">
							<div class="col-md-12 col-sm-12">
								<div id="faq">
									<div class="q"><?= $t->_('What is your support phone number?') ?></div>
									<div class="a">
										<?= $t->_('877-787-2929') ?>
									</div>
									<div class="q"><?= $t->_('I need to switch phones') ?></div>
									<div class="a">
										<?= $t->_('Simply re-enter your Leader team-specific activation code on another phone, and the hunt will pick up where you left off.') ?>
									</div>
									<div class="q"><?= $t->_('The app is not responding') ?></div>
									<div class="a">
										<?= $t->_('Refresh your browser. If the browser reloads the same screen after entering activation code, go into browser settings and accept cookies.') ?>
									</div>
									<div class="q"><?= $t->_('How are points calculated?') ?></div>
									<div class="a">
										<?= $t->_('Correct answer - Full points<br>Correct answer with a hint - Half points<br>Skip - No points') ?>
									</div>
									<div class="q"><?= $t->_('A challenge or location wasn’t there or had changed and I was unable to get the answer. Will I be docked points?') ?></div>
									<div class="a">
										<?= $t->_('Nope! We can manually add your points to your team if you shoot us a call.') ?>
									</div>
								</div>
							</div>
						</div>
				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>