<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<div class="container">
		<h1>My Products</h1>
		<ol class="breadcrumb">
			<li>
				<?= $this->tag->linkTo(['', "Home"]) ?>
			</li>
			<li class="active">
				<?= $this->tag->linkTo(['products', "<b>My Products</b>"]) ?>
			</li>
		</ol>
	</div>
</div>

<div class="container">
	<?= $this->getContent() ?>

	<?= $this->tag->linkTo(['products/new', 'Add a new product', 'class' => 'btn btn-primary']) ?><br><br>

	<div class="table-responsive">
		<table class="table table-striped table-hover table-custom table-options" id="products-list">
			<thead>
			<tr>
				<!--th>#</th-->
				<th>Name</th>
				<th>Address</th>
				<th>Price</th>
				<th>Created</th>
				<th>Actions</th>
			</tr>
			</thead>
		</table>
	</div>
</div>