<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Cities / <span style="font-size:80%"><?= $this->tag->linkTo(["cities/" . $country->id, htmlspecialchars($country->name)]) ?></span>
    </h1>
	<h2>
		Edit city
	</h2>
</div>

<?= $this->getContent() ?>

<?php
	echo $this->tag->form([
		"cities/save",
		"autocomplete" => "off",
		"class" => "form-horizontal"
	]);
echo $this->tag->hiddenField(["country_id", "type" => "number", "class" => "form-control", "id" => "fieldCountryId"]) ?>

<div class="form-group">
	<label for="fieldName" class="col-sm-2 control-label">Name</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldStatus" class="col-sm-2 control-label">Status</label>
	<div class="col-sm-10">
		<?= $this->tag->selectStatic([
			"status", [
				Cities::Active		=>	"Active",
				Cities::_New		=>	"New",
				Cities::ComingSoon	=>	"Coming Soon",
				Cities::ContactOnly	=>	"Contact Only",
				Cities::B2c			=>	"B2c"
			],
			'id' => 'fieldStatus'
		]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldStatus" class="col-sm-2 control-label">Timezone</label>
	<div class="col-sm-10">
		<?= $this->tag->selectStatic([
			'timezone',
			$timezones,
			'id' => 'fieldTimezone'
		]) ?>
	</div>
</div>

<?= $this->tag->hiddenField('id') ?>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?= $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
	</div>
</div>

<?= $this->tag->endForm() ?>
