<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?= $this->tag->linkTo(["countries", "Countries"]) ?></li>
		</ul>
	</nav>
</div>


<div class="page-header">
	<h1>
		Cities / <span style="font-size:80%"><?= $this->tag->linkTo(["cities/" . $country->id, htmlspecialchars($country->name)]) ?></span>
	</h1>
	<p>
		<a href="<?= $this->url->get("cities/new/" . $country->id) ?>" class="btn btn-success">Add a new city</a>
	</p>
</div>
<script type="text/javascript">window.countryId=<?= $country->id ?></script>
<?= $this->getContent() ?>


<div class="table-responsive">
	<table class="table table-striped table-hover table-custom table-options" id="cities-list">
		<thead>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Status</th>
			<th>Points</th>
			<th>Actions</th>
		</tr>
		</thead>
	</table>
</div>