<div class="row border-bottom">
	<nav class="navbar navbar-static-top" role="navigation" style="margin-bottom:0">
		<div class="navbar-header">
			<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
		</div>
		<ul class="nav navbar-top-links navbar-right">
			<li>
				<span class="m-r-sm text-muted welcome-message">Welcome to Strayboots admin</span>
			</li>
			<li>
				<span class="m-r-sm text-muted welcome-message">
					Server Clock: <span id="server-clock"></span>
					<?php ?>
					<script>
					(function(d,sc){
						var oTime=(new Date()).getTime(),
							dx=new Date(d.getTime());
						window.serverDate=dx;
						var x=function(){
							d=new Date(dx.getTime()+(new Date()).getTime()-oTime);
							var hours=d.getHours(),min=d.getMinutes(),
								sec=d.getSeconds(),mon=d.getMonth()+1,
								day=d.getDate(),ampm='AM';
							if(hours>11){if(hours>12)hours-=12;ampm='PM';}
							if(hours<10)hours='0'+hours;if(min<10)min='0'+min;
							if(day<10)day='0'+day;if(sec<10)sec='0'+sec;if(mon<10)mon='0'+mon;
							sc.innerText=mon+'/'+day+'/'+d.getFullYear()+' '+hours+':'+min+':'+sec+' '+ampm+' EST';
						};
						x();
						setInterval(x,1e3);
					})(new Date(<?php $today = getdate(); echo $today['year'].','.($today['mon'] - 1).','.$today['mday'].','.$today['hours'].','.$today['minutes'].','.$today['seconds']; ?>),document.getElementById('server-clock'))
					</script>
				</span>
			</li>
			<li>
				<a href="<?= $this->url->get("login/logout") ?>">
					<i class="fa fa-sign-out"></i> Log out
				</a>
			</li>
			<!--li>
				<a class="right-sidebar-toggle">
					<i class="fa fa-tasks"></i>
				</a>
			</li-->
		</ul>
	</nav>
</div>