<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?= $this->tag->linkTo(["blocked", "Back"]) ?></li>
		</ul>
	</nav>
</div>

<div class="page-header">
	<h1>
		Edit blocked email
	</h1>
</div>

<?= $this->getContent() ?>

<?php
	echo $this->tag->form([
		"blocked/save/" . $email,
		"autocomplete" => "off",
		"class" => "form-horizontal"
	]);
?>

<div class="form-group">
	<label for="fieldEmail" class="col-sm-2 control-label">Email</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?= $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
	</div>
</div>

<?= $this->tag->endForm() ?>
