<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<h1>
		Blocked emails
	</h1>
	<p>
		<a href="<?= $this->url->get('blocked/new') ?>" class="btn btn-success">Add a blocked email</a>
	</p>
</div>

<?= $this->getContent() ?>

<div class="table-responsive">
	<table class="table table-striped table-hover table-custom table-options" id="blocked-list">
		<thead>
		<tr>
			<th>Email</th>
			<th>Actions</th>
		</tr>
		</thead>
	</table>
</div>
