<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<div class="container">
<? $orderName = htmlspecialchars($orderHunt->Order->name);
	$huntName = htmlspecialchars($orderHunt->Hunt->name); ?>
		<h1><?= $orderName . ' // ' . $huntName . ' (' . date($dateFormat, strtotime($orderHunt->start)) ?>)</h1>
		<ol class="breadcrumb">
			<li>
				<?= $this->tag->linkTo(['', 'Home']) ?>
			</li>
			<li>
				<?= $this->tag->linkTo(['orders', 'My Orders']) ?>
			</li>
			<li>
				<?= $this->tag->linkTo(['order_hunts/' . $orderHunt->order_id, $orderName . ' Hunts']) ?>
			</li>
			<li class="active">
				<?= $this->tag->linkTo(['teams/' . $orderHunt->id, '<b>Teams</b>']) ?>
			</li>
		</ol>
	</div>
</div>

<? $this->partial('partials/orderhuntsmenu') ?>

<div class="container">

	<div class="note">
		<p>
			This is your teams’ planner. We've created this tool to help you arrange your teams better and assign the leader and players for each team.<br>
			<br>
			A few notes:<br>
			<ul>
				<li>This is only for planning. All players will have to login independently once the event begins.</li>
				<li>Use the “Export” button if you want to share the teams with all the players before the event.</li>
				<li>Make sure to mix people from different departments/teams to maximize the team bonding.</li>
			</ul>
		</p>
	</div>


	<?= $this->getContent() ?>
	<script type="text/javascript">window.orderId=<?= $order->id ?>;window.teams=<?= json_encode($teams, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?>;window.order_hunt=<?= json_encode($orderHunt->toArray(), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?></script>

	<div class="row">
		<div class="col-sm-12">
			<a href="pull-right">
			<?= $this->tag->linkTo(['teams/csv/' . $orderHunt->id, 'Export', 'class' => 'pull-right btn btn-warning']) ?>
			<h3>Participants: <span class="playersCount">0</span>/<?= $orderHunt->max_players ?></h3>
		</div>
	</div>

	<div class="row" style="margin-top:15px">
<? if ($huntStarted): ?>
		<script type="text/javascript">window.huntStarted=1;</script>
		<div class="col-sm-12">
			<div class="alert alert-danger">
				<b>Can't make changes!</b> Hunt has already begun
			</div>
		</div>
<? else: ?>
		<form method="post" id="add-player">
		<div class="col-sm-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h5>Add player</h5>
				</div>
				<div class="ibox-content">
					<div class="row">
						<div class="form-group col-sm-12 col-sd-6 col-lg-3">
							<label for="add-firstName" class="control-label">First Name</label>
							<input type="text" name="add-firstName" id="add-firstName" class="form-control" value="" required>
						</div>
						<div class="form-group col-sm-12 col-sd-6 col-lg-3">
							<label for="add-lastName" class="control-label">Last Name</label>
							<input type="text" name="add-lastName" id="add-lastName" class="form-control" value="" required>
						</div>
						<div class="form-group col-sm-12 col-sd-6 col-lg-3">
							<label for="add-email" class="control-label">Email</label>
							<input type="email" name="add-email" id="add-email" class="form-control" value="" required>
						</div>
						<div class="form-group col-sm-12 col-sd-6 col-lg-3">
							<label for="add-team" class="control-label">Team</label>
							<select name="add-team" id="add-team" class="select2-auto form-control" required>
								<?php foreach ($teams as $i => $team): ?>
									<option value="<?= $team['id'] ?>">Team #<?= $i + 1 ?></option>
								<?php endforeach ?>
							</select>
						</div>
						<div class="form-group col-sm-12" style="width:auto;float:right">
							<input type="submit" name="submit" id="add-submit" class="btn btn-success" value=" Add ">
						</div>
					</div>
				</div>
			</div>
		</div>
		</form>
<? endif ?>
</div>

	<?php
		echo $this->tag->form([
			'teams/save',
			'class' => 'form-horizontal',
			'id' => 'main-form'
		]);
	?>

	<div class="row<? if ($huntStarted) echo ' nosort'; ?>" id="teams"></div>

	<?= $this->tag->hiddenField(['players', 'id' => 'playersField']) ?>
	<?= $this->tag->hiddenField(['teams', 'id' => 'teamsField']) ?>
	<?= $this->tag->hiddenField('id') ?>

	<div class="form-group">
		<div class="col-sm-12">
			<?= $this->tag->submitButton(['Save', 'class' => 'btn btn-default'] + ($huntStarted ? ['disabled' => 'disabled'] : [])) ?>
		</div>
	</div>

	<div class="modal fade" id="codes" tabindex="-1" role="dialog" aria-labelledby="codesLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
					<h4 class="modal-title" id="codesLabel">Team #<span></span> activation codes</h4>
				</div>
				<div class="modal-body" style="font-size:20px">
					Leader: <span class="leader" style="color:red"></span><br>
					Player: <span class="player" style="color:blue"></span>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>

	<?= $this->tag->endForm() ?>
</div>
