<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?= $this->tag->linkTo(['orders', 'Orders']) ?></li>
		</ul>
	</nav>
</div>


<div class="page-header">
	<h1>
		Orders / <span style="font-size:80%"><?= $this->tag->linkTo(['orders/edit/' . $order->id, 'Order #' . $order->id . ' ' . htmlspecialchars($order->name) . ' <small>' . htmlspecialchars($client->first_name . ' ' . $client->last_name) . '</small>']) ?></span>
	</h1>
	<p>
		<a href="<?= $this->url->get('order_hunts/new/' . $order->id) ?>" class="btn btn-success">Add hunt</a> &nbsp; 
		<!--a href="javascript:;" data-id="<?= $order->id ?>" class="btn btn-warning sendmail">Mail</a-->
	</p>
</div>

<script type="text/javascript">window.orderId=<?= $order->id ?>;window.clientName="<?= $this->escaper->escapeHtmlAttr($client->first_name . ' ' . $client->last_name . ' (' . $client->company . ')') ?>";window.orderName="<?= $this->escaper->escapeHtmlAttr($order->name) ?>"</script>

<?= $this->getContent() ?>

<script type="text/javascript">
window.countries=<?= json_encode($countries, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;
window.cities=<?= json_encode($cities, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;
</script>

<div class="table-responsive">
	<table class="table table-striped table-hover table-custom table-options" id="orderhunts-list">
		<thead>
		<tr>
			<th>#</th>
			<th>Hunt</th>
			<th>City / Country</th>
			<th>Players</th>
			<th>Teams</th>
			<th>Start</th>
			<th>Finish</th>
			<th>Expire</th>
			<th>Actions</th>
		</tr>
		</thead>
	</table>
</div>