<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<h1>
		Questions
		<? if (isset($tag)): ?><small><?= $tag ?></small><? endif ?>
	</h1>
	<p>
		<a href="<?= $this->url->get('questions/new') ?>" class="btn btn-success">Add a new question</a> &nbsp;
		<a href="<?= $this->url->get('questions/XLSX') ?>" class="btn btn-primary">XLSX</a>
	</p>
</div>

<?= $this->getContent() ?>

<script type="text/javascript">window.questionTypes=<?= json_encode($questionTypes, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?></script>

<div class="table-responsive">
	<table class="table table-striped table-hover table-custom table-options" id="questions-list">
		<thead>
		<tr>
			<th>#</th>
			<th>Question</th>
			<th>Type</th>
			<th>Point</th>
			<th>Score</th>
			<th>Hunt Points</th>
			<th>Submittions</th>
			<th>Wrong</th>
			<th>Tags</th>
			<th>Actions</th>
		</tr>
		</thead>
	</table>
</div>