<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?= $this->tag->linkTo(["questions", "Back"]) ?></li>
		</ul>
	</nav>
</div>

<div class="page-header">
	<h1>
		Wrong answers for <a href="<?= $this->url->get('questions/edit/' . $question->id) ?>"><small><?= $question->question ?></small></a>
	</h1>
</div>

<?= $this->getContent() ?>

<div class="table-responsive">
	<table class="table table-striped table-hover table-custom table-options" id="wrong-list">
		<thead>
		<tr>
			<th>#</th>
			<th>Order Hunt</th>
			<th>Answer</th>
			<th>Timestamp</th>
			<th>Actions</th>
		</tr>
		</thead>
	</table>
</div>

<script type="text/javascript">window.qid=<?= $question->id ?></script>
