		<div id="chat">
			<div id="chat-textbox" class="clearfix">
				<div class="upload-progress"></div>
				<textarea></textarea>
				<button type="button" class="chat-button"><?= $t->_('Post') ?></button>
				<div class="upload-container">
					<i></i>
					<input id="chat-files" type="file" name="files[]" multiple="multiple" accept="image/*">
				</div>
			</div>
			<div class="app_loading"></div>
		</div>
