<div class="row  border-bottom white-bg dashboard-header">
	<div class="col-sm-3">
		<h2>Welcome</h2>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<h3 style="margin:25px 0">Active hunts</h3>
		<div class="table-responsive">
			<table class="table index-table table-striped table-hover table-custom table-options" id="active-hunts">
				<thead>
				<tr>
					<th>#</th>
					<th>Order</th>
					<th>Hunt</th>
					<th>City</th>
					<th>Company</th>
					<th>Teams/Players</th>
					<th>Start</th>
					<th>Finish</th>
					<th>Start (local)</th>
					<th>Finish (local)</th>
					<th></th>
				</tr>
				</thead>
			</table>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<h3 style="margin:25px 0">Last week hunts</h3>
		<div class="table-responsive">
			<table class="table index-table table-striped table-hover table-custom table-options" id="last-hunts">
				<thead>
				<tr>
					<th>#</th>
					<th>Order</th>
					<th>Hunt</th>
					<th>City</th>
					<th>Company</th>
					<th>Teams/Players</th>
					<th>Start</th>
					<th>Finish</th>
					<th>Start (local)</th>
					<th>Finish (local)</th>
					<th></th>
				</tr>
				</thead>
			</table>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<h3 style="margin:25px 0">Coming hunts</h3>
		<div class="table-responsive">
			<table class="table index-table table-striped table-hover table-custom table-options" id="coming-hunts">
				<thead>
				<tr>
					<th>#</th>
					<th>Order</th>
					<th>Hunt</th>
					<th>City</th>
					<th>Company</th>
					<th>Teams/Players</th>
					<th>Start</th>
					<th>Finish</th>
					<th>Start (local)</th>
					<th>Finish (local)</th>
					<th></th>
				</tr>
				</thead>
			</table>
		</div>
	</div>
</div>

<div id="blueimp-gallery" class="blueimp-gallery">
	<div class="slides"></div>
	<h3 class="title"></h3>
	<a class="prev">‹</a>
	<a class="next">›</a>
	<a class="close">×</a>
	<a class="play-pause"></a>
	<ol class="indicator"></ol>
</div>
