<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<div class="container">
		<h1><?= htmlspecialchars($orderHunt->Order->name . ' // ' . $orderHunt->Hunt->name) . ' (' . date($dateFormat, strtotime($orderHunt->start)) ?>) <small>Edit Bonus Question #<?= $id ?></small></h1>
		<ol class="breadcrumb">
			<li>
				<?= $this->tag->linkTo(['', 'Home']) ?>
			</li>
			<li>
				<?= $this->tag->linkTo(['orders', 'Orders']) ?>
			</li>
			<li>
				<?= $this->tag->linkTo(['order_hunts/' . $orderHunt->order_id, 'Order hunts']) ?>
			</li>
			<li>
				<?= $this->tag->linkTo(['bonus/' . $orderHunt->id, 'Bonus']) ?>
			</li>
			<li class="active">
				<?= $this->tag->linkTo(['bonus/edit/' . $id, '<b>Edit</b>']) ?>
			</li>
		</ol>
	</div>
</div>

<? $this->partial('partials/orderhuntsmenu') ?>

<div class="container">
<? /*if ($huntStarted): ?>
	<script type="text/javascript">window.huntStarted=1;</script>
	<div class="row">
		<div class="col-sm-12">
			<div class="alert alert-danger">
				<b>Can't make changes!</b> Hunt has already begun
			</div>
		</div>
	</div>
<? else:*/ ?>

	<?= $this->getContent() ?>

	<?php
		echo $this->tag->form([
			'bonus/save',
			'autocomplete' => 'off',
			'class' => 'form-horizontal customize-form'
		]);
	?>

	<div class="form-group">
		<label for="fieldType" class="col-sm-2 control-label">Type</label>
		<div class="col-sm-10">
			<?= $this->tag->selectStatic([
				'type', [
					BonusQuestions::TypeTeam		=> 'Team',
					//BonusQuestions::TypePrivate		=> 'Private'
				],
				'id' => 'fieldType',
				'class' => 'form-control'
			]) ?>
		</div>
	</div>

	<div class="form-group">
		<label for="fieldQuestion" class="col-sm-2 control-label">Question</label>
		<div class="col-sm-10">
			<?= $this->tag->textArea(['question', 'cols' => 30, 'rows' => 4, 'class' => 'form-control', 'id' => 'fieldQuestion']) ?>
		</div>
	</div>

	<div class="form-group">
		<label for="fieldAnswers" class="col-sm-2 control-label">Answers<br><small>Add as many answers as you want, every answer in a new line</small></label>
		<div class="col-sm-10">
			<?= $this->tag->textArea(['answers', 'cols' => 30, 'rows' => 4, 'class' => 'form-control', 'id' => 'fieldAnswers']) ?>
		</div>
	</div>

	<div class="form-group">
		<label for="fieldScore" class="col-sm-2 control-label">Score</label>
		<div class="col-sm-10">
			<?= $this->tag->numericField(['score', 'type' => 'number', 'min' => 0, 'class' => 'form-control', 'id' => 'fieldScore']) ?>
		</div>
	</div>

	<input type="hidden" name="order_hunt_id" value="<?= $orderHunt->id ?>">
	<?= $this->tag->hiddenField("id") ?>

	<div class="form-group">
		<div class="col-sm-12">
			<?= $this->tag->submitButton(['Save', 'class' => 'btn btn-default']) ?>
		</div>
	</div>

	<?= $this->tag->endForm() ?>

<? //endif ?>
</div>