<!DOCTYPE html>
<html style="background:#474141">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title><?= isset($customTitle) ? $customTitle : 'Strayboots' ?></title>
	<script>(new Image()).src='/img/bgn-2.jpg';</script>
	<link rel="preload" href="/img/bgn-2.jpg" as="image">
	<script>
		window.isLeader=!<?= isset($isLeader) && $isLeader ? 0 : 1 ?>;
		window.loadTime=new Date;
		(function(vp,de){
			var setVP=function(){
				var ww=window.outerWidth||de.clientWidth,
					w='device-width, initial-scale=1.0, maximum-scale=1.0';
				/*if(ww<480){*/
					if(ww<360)
						w=360;
					/*else 
						w=480;
				}*/
				vp.setAttribute('content','width='+w+', user-scalable=no');
			};
			setVP();
			window.addEventListener('orientationchange',setVP,false);
			window.addEventListener('resize',setVP,false);
		})(document.querySelector('meta[name="viewport"]'),document.documentElement);
	</script>
<? if (isset($headerHTML)) echo $headerHTML; ?>
	<link href='//fonts.googleapis.com/css?family=Open+Sans:400,600,300,800|Roboto:400,500,700,900,300' rel='stylesheet' type='text/css'>
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<? if (isset($assetsCache))
		echo '<link rel="stylesheet" type="text/css" href="/' . $assetsCache . '.css" />';
	else
		$this->assets->outputCss('style');
	?>
<? if (isset($huntCss)): ?>	<style type="text/css"><?= $huntCss ?></style><? endif ?>
<? /*echo '<script src="http://10.0.0.12:8080/target/target-script-min.js#anonymous"></script>';*/ ?>
<? if (isset($ncr) && $ncr): ?>	<script>window.ncrHunt=!0</script><? endif ?>

</head>
<body class="body-element controller-<?= $controllerName ?>">
	<div class="main-section">
<?= $this->partial('partials/header') ?>
<?= $this->getContent() ?>
<?= $this->partial('partials/footer') ?>
	</div>
<? if (isset($audio)): ?>
	<audio hidden="hidden" id="main-audio">
<? foreach ($audio as $source): ?>
		<source src="<?= $source[0] ?>" type="<?= $source[1] ?>">
<? endforeach ?>
	</audio>
	<script>
	var ma = document.getElementById('main-audio');
	ma.play();
	if (document.getElementById('main-audio').paused) {
		document.getElementsByTagName('body')[0].addEventListener('touchstart', function(e){
			e.target.removeEventListener(e.type, arguments.callee);
			ma.play();
		});
	}
	</script>
<? endif ?>
<? if (isset($firebase)): ?>
	
	<? if (isset($firebase['config'])): ?><script src="//www.gstatic.com/firebasejs/4.8.1/firebase.js"></script><? endif ?>
	<script><? if (isset($order_hunt_id)) echo "window.order_hunt_id={$order_hunt_id};"; ?>window.appLoc=<?= json_encode($firebase['appLoc'], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?>;window.FB_PREFIX='<?= FB_PREFIX ?>';<? if (isset($firebase['config'])) echo 'firebase.initializeApp(' . json_encode($firebase['config'], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ');'; ?></script>
<? endif ?>
<? if (isset($facebookSDK)): ?>
	<script>
	(function(){
		var fbFuncs=[],fbLoaded=!1;
		window.fbFunc=function(f){if(typeof f=='function')fbFuncs.push(f);
		if(fbLoaded)for(var i=0;i<fbFuncs.length;i++)try{fbFuncs[i]()}catch(E){}};
		window.fbAsyncInit=function(){
			FB.init({
				appId: '302564933413297',
				status: true,
				xfbml: true,
				version: 'v2.7'
			});
			fbLoaded = true;
			window.fbFunc();
		};
	})();
	</script>
	<script src="//connect.facebook.net/en_US/sdk.js" id="facebook-jssdk"></script>
<? endif ?>
	<?
	if (isset($assetsCache))
		echo '<script src="/' . $assetsCache . '.js"></script>';
	else
		$this->assets->outputJs('script');
	if (!empty($msgs = $this->flash->getMessages())): ?>

	<script>
		$(function(){
<? $x = 0; foreach ($msgs as $type => $msg):
			foreach ($msg as $m): ?>
			setTimeout(function(){
				toastr.<?= $type ?>(null, "<?= $this->escaper->escapeHtmlAttr($m) ?>");
			}, <?= 500 + $x++ * 1000 ?>);
<? endforeach; endforeach ?>
		});
	</script>
<? endif ?>
<? if (isset($googleMaps)): ?>
	<script src="//maps.googleapis.com/maps/api/js?key=<?= $googleMaps ?>&callback=initMap"></script>
<? endif ?>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create','UA-7559873-20','auto');ga('send','pageview');
</script>
<script>var google_conversion_id=1027606727,google_conversion_label="8We6CKOB8GoQx5GA6gM",google_custom_params=window.google_tag_params,google_remarketing_only=true;</script>
<script src="//www.googleadservices.com/pagead/conversion.js"></script>
</body>
</html>