<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?= $this->tag->linkTo(['custom_events/index/' . $orderHunt->id, 'Go Back']) ?></li>
		</ul>
	</nav>
</div>

<div class="page-header">
	<h1>
		Add a new custom event
	</h1>
</div>

<?= $this->getContent() ?>

<?php
	echo $this->tag->form([
		"custom_events/create",
		"autocomplete" => "off",
		"class" => "form-horizontal"
	]);
?>
<?= $this->tag->hiddenField(["order_hunt_id"]) ?>

<div class="form-group">
	<label for="fieldName" class="col-sm-2 control-label">Title</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldTypeId" class="col-sm-2 control-label">Team</label>
	<div class="col-sm-10">
		<?= $this->tag->select([
			'team_id',
			Teams::find('order_hunt_id=' . $orderHunt->id),
			'id'			=> 'fieldTeamId',
			'class'			=> 'form-control select2-auto',
			'using'			=> ['id', "name"],
			'useEmpty'		=> true,
			'emptyText'		=> '',
			'emptyValue'	=> ''
		]); ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldScore" class="col-sm-2 control-label">Score</label>
	<div class="col-sm-10">
		<?= $this->tag->numericField(["score", "type" => "number", 'min' => 0, "class" => "form-control", "id" => "fieldScore"]) ?>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?= $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
	</div>
</div>

<?= $this->tag->endForm() ?>
