<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<h1>
		Countries
	</h1>
	<p>
		<a href="<?= $this->url->get('countries/new') ?>" class="btn btn-success">Add a new country</a>
	</p>
</div>

<?= $this->getContent() ?>

<div class="table-responsive">
	<table class="table table-striped table-hover table-custom table-options" id="countries-list">
		<thead>
		<tr>
			<th>#</th>
			<th>Country</th>
			<th>Cities</th>
			<th>Actions</th>
		</tr>
		</thead>
	</table>
</div>