<div class="row white-bg">
	<nav class="navbar navbar-static-top" role="navigation">
		<div class="navbar-header">
<? if ($supplierLogin): ?>
			<button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button"><i class="fa fa-reorder"></i></button>
<? endif ?>
			<a href="<?= $this->url->get('') ?>" class="navbar-brand"><img src="/img/logo.png" width="98" height="30"></a>
		</div>
		<div class="navbar-collapse collapse" id="navbar">
<? if ($supplierLogin): ?>
			<ul class="nav navbar-nav">
				<li>
					<a href="<?= $this->url->get("") ?>">Home</a>
				</li>
				<li>
					<a href="<?= $this->url->get("products") ?>">My Products</a>
				</li>
			</ul>
			<ul class="nav navbar-top-links navbar-right">
				<li>
					<a href="<?= $this->url->get("login/logout") ?>">
						<i class="fa fa-sign-out"></i> Log out
					</a>
				</li>
			</ul>
<? endif ?>
		</div>
	</nav>
</div>