
<div class="page-header">
	<div class="container">
		<h1 style="margin-bottom:0">Welcome To Strayboots</h1>
	</div>
</div>

<div class="container">

	<div class="row">
		<div class="col-sm-12">
			<h3 style="margin:25px 0">Team Apparel to Fuel Your Adventure</h3>
			<div class="form-horizontal">
				Strayboots Team Gear is the place to visit for team apparel to boost the success of your mobile scavenger hunt or team building activity.<br>Every product has been specially selected to ensure quality, comfort, value, and style.<br>Order your team apparel and accessories from Strayboots Team Gear, and take the guesswork out of shopping!<br><br>
				<a class="btn btn-success" href="https://www.straybootsgear.com/" target="_blank">START NOW!</a>
			</div>
		</div>
	</div>

<? if (!empty($activeHunts)): ?>
	<div class="row">
		<div class="col-sm-12">
			<h3 style="margin:25px 0">Active hunts</h3>
<? foreach ($activeHunts as $h): ?>
			<div class="row">
				<div class="col-sm-12">
					<div data-id="<?= $h['id'] ?>" class="orderhunt-box ibox float-e-margins border-bottom">
						<div class="ibox-title">
							<h5><a href="<?= $this->url->get('order_hunts/' . $h['order_id']) ?>"><?= htmlspecialchars($h['name']) ?></a> // <a href="<?= $this->url->get('order_hunts/summary/' . $h['id']) ?>"><?= htmlspecialchars($h['huntname']) ?></a> // <?= date($dateFormat, strtotime($h['start'])) ?></h5>
							<div class="ibox-tools">
								<a href="<?= $this->url->get('order_hunts/summary/' . $h['id']) ?>" class="btn btn-success">View</a>
								<a href="javascript:;" class="collapse-link"><i class="fa fa-chevron-down"></i></a>
							</div>
						</div>
						<div class="ibox-content"></div>
					</div>
				</div>
			</div>
<? endforeach ?>
		</div>
	</div>

	<div id="blueimp-gallery" class="blueimp-gallery">
		<div class="slides"></div>
		<h3 class="title"></h3>
		<a class="prev">‹</a>
		<a class="next">›</a>
		<a class="close">×</a>
		<a class="play-pause"></a>
		<ol class="indicator"></ol>
	</div>

<? endif ?>

	<div class="row">
		<div class="col-sm-12">
			<h3 style="margin:25px 0">My Orders</h3>
			<div class="table-responsive my-orders">
				<table class="table table-striped table-hover table-custom table-options" id="orders-list">
					<thead>
					<tr>
						<!--th>#</th-->
						<th>Name</th>
						<th>Created</th>
						<th>Hunts</th>
						<th>Actions</th>
					</tr>
					</thead>
				</table>
			</div>
		</div>
	</div>
</div>
