<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?= $this->tag->linkTo(["login_pages", "Back"]) ?></li>
		</ul>
	</nav>
</div>

<div class="page-header">
	<h1>
		Edit a login page
	</h1>
</div>

<?= $this->getContent() ?>

<?php
	echo $this->tag->form([
		"login_pages/save",
		"autocomplete" => "off",
		"class" => "form-horizontal"
	]);
?>

<div class="form-group">
	<label for="fieldSlug" class="col-sm-2 control-label">Slug</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["slug", "size" => 30, "class" => "form-control", "id" => "fieldSlug"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldTitle" class="col-sm-2 control-label">Title</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldWelcomeTitle" class="col-sm-2 control-label">Welcome title</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["welcome_title", "size" => 30, "class" => "form-control", "id" => "fieldWelcomeTitle"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldOrderHunt" class="col-sm-2 control-label">OrderHunt</label>
	<div class="col-sm-10">
		<?= $this->tag->selectStatic([
			'order_hunt_id',
			$orderHunts,
			'id' => 'fieldOrderHunt'
		]) ?>
	</div>
</div>

<style>
	#e1:not(.hidden) + #e2 {
		display: none !important;
	}
	.col-sm-10 > input[type="checkbox"] {
		margin-top: 10px;
	}
</style>

<div class="form-group">
	<label for="fieldIsEmailLogin" class="col-sm-2 control-label">Email only</label>
	<div class="col-sm-10">
		<input type="checkbox" id="fieldIsEmailLogin" onclick="$('#fieldEmailLogin').closest('.form-group').toggleClass('hidden', !this.checked);this.checked || $('#fieldEmailLogin').val('')"
				<?= empty($this->tag->getValue('email_login')) ? '' : ' checked' ?>> 
	</div>
</div>

<div class="form-group<?= empty($this->tag->getValue('email_login')) ? ' hidden' : '' ?>" id="e1">
	<label for="fieldEmailLogin" class="col-sm-2 control-label">Email</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["email_login", "size" => 30, "class" => "form-control", "id" => "fieldEmailLogin"]) ?>
	</div>
</div>

<div class="form-group" id="e2">
	<label for="fieldActivationCodeLogin" class="col-sm-2 control-label">Use Activation Code</label>
	<div class="col-sm-10">
		<?= $this->tag->checkField(['activation_code_login', 'value' => 1, 'id' => 'fieldActivationCodeLogin']) ?>
	</div>
</div>

<?= $this->tag->hiddenField('id') ?>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?= $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
	</div>
</div>

<?= $this->tag->endForm() ?>
