<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<h1>
		Login Pages
	</h1>
	<p>
		<a href="<?= $this->url->get('login_pages/new') ?>" class="btn btn-success">Add a new login page</a>
	</p>
</div>

<?= $this->getContent() ?>

<div class="table-responsive">
	<table class="table table-striped table-hover table-custom table-options" id="loginpages-list">
		<thead>
		<tr>
			<th>#</th>
			<th>Slug</th>
			<th>Title</th>
			<th>Sub Title</th>
			<th>OrderHunt</th>
			<th>Actions</th>
		</tr>
		</thead>
	</table>
</div>