<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?= $this->tag->linkTo(["login_pages", "Go Back"]) ?></li>
		</ul>
	</nav>
</div>

<div class="page-header">
	<h1>
		Add a new login page
	</h1>
</div>

<?= $this->getContent() ?>

<?php
	echo $this->tag->form([
		"login_pages/create",
		"autocomplete" => "off",
		"class" => "form-horizontal"
	]);
?>

<div class="form-group">
	<label for="fieldSlug" class="col-sm-2 control-label">Slug</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["slug", "size" => 30, "class" => "form-control", "id" => "fieldSlug"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldTitle" class="col-sm-2 control-label">Title</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["title", "size" => 30, "class" => "form-control", "id" => "fieldTitle"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldWelcomeTitle" class="col-sm-2 control-label">Welcome title</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["welcome_title", "size" => 30, "class" => "form-control", "id" => "fieldWelcomeTitle"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldOrderHunt" class="col-sm-2 control-label">OrderHunt</label>
	<div class="col-sm-10">
		<?= $this->tag->selectStatic([
			'order_hunt_id',
			$orderHunts,
			'id' => 'fieldOrderHunt'
		]) ?>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?= $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
	</div>
</div>

<?= $this->tag->endForm() ?>
