
	<div class="container">
		<div class="middle-box text-center loginscreen animated fadeInDown">
			<div>
				<div style="text-align:center;margin-bottom:50px">
					<img src="https://www.strayboots.com/media/static/img/home/logo.png" height="66" width="215">
				</div>
				<h3>Welcome to Strayboots</h3>
				<p>The all-new Strayboots admin panel</p>
				<p>Login in. To see it in action.</p>
				<form class="m-t" role="form" method="post" action="<?= $this->url->get("login/login") ?>">
					<div class="form-group">
						<input type="email" name="email" class="form-control" placeholder="Email" required="">
					</div>
					<div class="form-group">
						<input type="password" name="password" class="form-control" placeholder="Password" required="">
					</div>
					<input type="hidden" name="<?= $this->security->getTokenKey() ?>" value="<?= $this->security->getToken() ?>" />
					<button type="submit" class="btn btn-primary block full-width m-b">Login</button>
				</form>
				<p class="m-t"> <small>Strayboots &copy; 2016</small> </p>
			</div>
		</div>
	</div>