<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
	<h1>
		Orders <? if ($client): ?> <small>Client: <?= htmlspecialchars($client->first_name . ' ' . $client->last_name . ' (' . $client->company . ')') ?></small><script type="text/javascript">window.clientId=<?= $client->id ?></script><? endif; ?> <? if ($hunt): ?> <small>Hunt: <?= htmlspecialchars($hunt->name) ?></small><script type="text/javascript">window.huntId=<?= $hunt->id ?></script><? endif; ?>
	</h1>
	<p>
		<a href="<?= $this->url->get('orders/new') ?>" class="btn btn-success">New order</a> &nbsp;
		<a href="<?= $this->url->get('orders/XLSX') ?>" class="btn btn-primary">XLSX</a>
	</p>
</div>

<?= $this->getContent() ?>

<div class="table-responsive">
	<table class="table table-striped table-hover table-custom table-options" id="orders-list">
		<thead>
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Client</th>
			<th>Company</th>
			<th>Created</th>
			<th>Hunts</th>
			<th>Actions</th>
		</tr>
		</thead>
	</table>
</div>