<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?= $this->tag->linkTo(["orders", "Go Back"]) ?></li>
		</ul>
	</nav>
</div>

<div class="page-header">
	<h1>
		New order
	</h1>
</div>

<?= $this->getContent() ?>

<?php
	echo $this->tag->form([
		"orders/create",
		"autocomplete" => "off",
		"class" => "form-horizontal"
	]);
?>

<div class="form-group">
	<label for="fieldName" class="col-sm-2 control-label">Name</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldClientId" class="col-sm-2 control-label">Client</label>
	<div class="col-sm-10">
		<?= $this->tag->selectStatic([
			'client_id',
			$clients,
			'class'			=> 'form-control select2-auto',
			'id'			=> 'fieldClientId',
			'using'			=> ['id', "name"],
			'useEmpty'		=> true,
			'emptyText'		=> '',
			'emptyValue'	=> ''
		]); ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldCodePrefix" class="col-sm-2 control-label">Code Prefix</label>
	<div class="col-sm-10">
		<?= $this->tag->textField(["code_prefix", "size" => 30, "class" => "form-control", "id" => "fieldCodePrefix"]) ?>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?= $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
	</div>
</div>

<?= $this->tag->endForm() ?>
